version: "3.8"
services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile_dev
    volumes:
      - ./penguin-pipeline:/penguin-pipeline
      - ./models:/models
      - ./data:/data
    ports:
      - "8888:8888"
    entrypoint: [ "jupyter", "lab", "--allow-root", "--ip",  "0.0.0.0",  "--no-browser" ]