apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: kubeflow
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: tfx-pvc
    - name: gcp-credentials-gcs-pipeline-output-sa
      secret:
        secretName: gcs-pipeline-output-sa
        defaultMode: 420
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/ddd/html"
          name: task-pv-storage
        - mountPath: /secret/gcp-credentials
          name: gcp-credentials-gcs-pipeline-output-sa
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/gcp-credentials/gcs-pipeline-output-sa.json
        - name: CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE
          value: /secret/gcp-credentials/gcs-pipeline-output-sa.json